### PR TITLE
Various bug fixes and updates

### LINKED ISSUE #13: items left does not update
Checking and unchecking items does not update the number of items left.

### PR DESCRIPTION
**Pull request by ztoben**
Closes #13, #14, #15

Checked item total wasn't updating correctly. I'm assuming because it was bound more than a level deep in the items list? Maybe you can clear that up for me. If there's a better way to do this let me know, thanks. Also updated the dependencies, scripts, and rollup config to reflect the latest sveltejs/template.

Before:

After:

### CODE REVIEW

**Comment by dux** [comment]
while you are doing updates in hopes of a merge, you can also optimize class:selected

        <li><a class:selected="{currentFilter === 'all'}" href="#/">All</a></li>
        <li><a class:selected="{currentFilter === 'active'}" href="#/active">Active</a></li>
        <li><a class:selected="{currentFilter === 'completed'}" href="#/completed">Completed</a></li>

**Comment by theodore-s-beers** [comment]
Any idea why this hasn't been merged? There are a few other issues that I've found, with simple fixes, but I'm not sure it makes sense to take the time to write them up or create a new PR.

e.g.1, the `createNew` function doesn't check that some text has actually been entered, so it will happily add empty todo items. (I added a check for `event.target.value.length > 0`.)

e.g.2, `autofocus` in the edit field doesn't work properly in Chrome or Firefox. (It does in Safari, for whatever reason.) Double-clicking an item should apply focus to the edit field once it appears. The only way I was able to fix this reliably was to make the edit field a separate component—hence with its own lifecycle—and to apply focus with an `onMount` function.

**Comment by ztoben** [comment]
@theodore-s-beers, I'm assuming they just aren't interested in maintaining it at this point. Would be nice if they at least marked the repo as deprecated so people know to look elsewhere for an up to date version.

**Comment by theodore-s-beers** [comment]
Maybe TodoMVC isn't seen as relevant anymore? Their own repo looks dormant. On the bright side, making a fixed version of this has been a nice part of my experience getting started with Svelte. I also used TypeScript, which became available recently. Anyway, thank you for sharing this PR!

**Pull request closed without merging**
